### ISSUE TITLE
Jest Test run fails on alert-controller.js

### ISSUE THREAD

**Issue by damian-tarnawsky** [datencia/ionic2-jest-example#12]
Using this tutorial to add Jest to an Ionic 3 project we get a failure to run tests:

>     \node_modules\ionic-angular\components\alert\alert-controller.js:1
>     ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { Injectable } from '@angular/core';
>                                                                                              ^^^^^^
> 
>     SyntaxError: Unexpected token import

To resolve this problem the instructions need to add ionic-angular to the transformIgnorePatterns:
```
"transformIgnorePatterns": [
      "node_modules/(?!@ngrx|@ionic-native|ionic-angular|@ionic)"
    ]
```

I can contribute a pull request if you like

**Comment by datencia** [comment]
Hi, sorry for the delay...

really? let me check it out first

**Comment by datencia** [comment]
Too late but I've added a couple of tests for an AlertController and seems it is working right. @damian-tarnawsky are you still facing that issue?
